language: minimal
sudo: require
services:
  - docker

before_script:
  - unset BUNDLE_GEMFILE
  - docker-compose run app bundle install
script:
  - docker-compose run app bundle exec rake

env:
- RAILS_ENABLED=0
- RAILS_ENABLED=1
